### ISSUE TITLE
React Native IOS Instructions

### ISSUE THREAD

**Issue by pineapplegreentea** [alibaba/GCanvas#153]
Please update the React Native setup guide as it is almost entirely outdated.
For those looking to integrate GCanvas for React Native on IOS follow these steps instead:

1) Create your React Native project
2) npm install @gcanvas/core --save
npm install react-native-gcanvas --save
3) Open the ios/.xcworkspace file in Xcode
4) Project Navigator -> Libraries directory -> right click -> add files -> select RCTGCanvas.xcodeproj from the react-native-gcanvas module
5) Project Navigator -> Frameworks directory -> right click -> add files as a group (check copy if needed)-> select GCanvas.framework from the react-native-gcanvas module
6) click on RCTGCanvas.xcodeproj in the Libraries directory -> build settings tab -> Header Search Path -> add the React entries: [PROJECT_PATH]/node_modules/react-native/ReactCommon/yoga, [PROJECT_PATH]/node_modules/react-native/ReactCommon, [PROJECT_PATH]/node_modules/react-native, [PROJECT_PATH]/ios/Pods/Headers/Public/React-Core, all with non-recursive flag
7) build
8) Project Navigator -> Build Phases tab -> Link Binary with Libraries -> + -> RCTGCanvas.xcodeproj/products/libRTGCanvas.a
9) clean and build

**Comment by likern** [comment]
@pineapplegreentea Have you tried to install GCanvas on Android? Might be you solve problems there...

**Comment by pineapplegreentea** [comment]
@likern No but I plan to within a month, depending on how the IOS side of the current project goes. It looks like they only pushed the app directory.

**Comment by likern** [comment]
> @likern No but I plan to within a month, depending on how the IOS side of the current project goes. It looks like they only pushed the app directory.

Please, share your result and how-to guide here.

I couldn't use GCanvas on Android due to errors on Android side of it.

Still tried to apply F2 (mobile charts which utilize canvas Web API), but using react-native-canvas and the result was sad - it was very slow  even with very simple chart (several columns bar chart) on powerful mobile.

Switched back to custom charts with react-native-svg.

**Comment by pineapplegreentea** [comment]
> > @likern No but I plan to within a month, depending on how the IOS side of the current project goes. It looks like they only pushed the app directory.
> 
> Please, share your result and how-to guide here.
> 
> I couldn't use GCanvas on Android due to errors on Android side of it.
> 
> Still tried to apply F2 (mobile charts which utilize canvas Web API), but using react-native-canvas and the result was sad - it was very slow even with very simple chart (several columns bar chart) on powerful mobile.
> 
> Switched back to custom charts with react-native-svg.

Will do. For info, I am getting 60+ fps one iPhone 11, so this probably will solve your performance issues. Too bad this project isn't actively maintained.

**Comment by drewandre** [comment]
@jwxbond how come this is closed? The instructions to build this on react-native 0.6x do not work. Are there plans to continue supporting react-native?

**Comment by flyskywhy** [comment]
@pineapplegreentea @likern @drewandre 

Since Alibaba [feat: delete weex bridge & reactive bridge](https://github.com/alibaba/GCanvas/commit/1bbee40a16c0c5da58698e2892ba33f836eedb70), here comes the [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) npm package.

After months work, [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) runs well on Android and iOS, fix several bugs and add `feat: support drawImage() from require('some.png') on Android, iOS and Web` described in [Changelog.md](https://github.com/flyskywhy/react-native-gcanvas/blob/master/docs/Changelog.md), refactor with the detailed [Example As Usage](https://github.com/flyskywhy/react-native-gcanvas#example-as-usage) in README.md.

With [Performance Test Result](https://github.com/flyskywhy/react-native-gcanvas#performance-test-result), and [Convenient With Browser-like canvas APIs](https://github.com/flyskywhy/react-native-gcanvas#convenient-with-browser-like-canvas-apis) with the easily `<canvas/>` ported example [react-native-particles-bg](https://github.com/flyskywhy/react-native-particles-bg) runs on Android, iOS and Web, `@flyskywhy/react-native-gcanvas` is the best choice for now :yum:
