### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by Still-a-man-you-will-never-get** [alibaba/GCanvas#154]
* What went wrong:
A problem occurred evaluating project ':react-native-gcanvas'.
> Extension with name 'sdks' does not exist. Currently registered extension names: [ext, _internalAndroidGradlePluginDependencyCheckerRegistered]

I do not what is the sdks, can you see see

**Comment by MatheusrdSantos** [comment]
I had the same issue yesterday when trying to build my RN project for android.

**Comment by Still-a-man-you-will-never-get** [comment]
Did you solve it, friend

**Comment by Still-a-man-you-will-never-get** [comment]
https://gitee.com/365t/react-native-f2demo/tree/master/src
You can try this demo. I successfully avoided this problem

**Comment by MatheusrdSantos** [comment]
I still have this issue. The link you shared may work, but I need some setup guides since the official guide is broken.

**Comment by Still-a-man-you-will-never-get** [comment]
Can you give me your email? I'll send you the compressed package, which needs to change a small file, but I haven't figured out why this error will occur when you install gcanvas according to normal steps on Android phones

**Comment by flyskywhy** [comment]
@Still-a-man-you-will-never-get @MatheusrdSantos 

Since Alibaba [feat: delete weex bridge & reactive bridge](https://github.com/alibaba/GCanvas/commit/1bbee40a16c0c5da58698e2892ba33f836eedb70), here comes the [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) npm package.

After months work, [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) runs well on Android and iOS, fix several bugs and add `feat: support drawImage() from require('some.png') on Android, iOS and Web` described in [Changelog.md](https://github.com/flyskywhy/react-native-gcanvas/blob/master/docs/Changelog.md), refactor with the detailed [Example As Usage](https://github.com/flyskywhy/react-native-gcanvas#example-as-usage) in README.md.

With [Performance Test Result](https://github.com/flyskywhy/react-native-gcanvas#performance-test-result), and [Convenient With Browser-like canvas APIs](https://github.com/flyskywhy/react-native-gcanvas#convenient-with-browser-like-canvas-apis) with the easily `<canvas/>` ported example [react-native-particles-bg](https://github.com/flyskywhy/react-native-particles-bg) runs on Android, iOS and Web, `@flyskywhy/react-native-gcanvas` is the best choice for now :yum:
