### ISSUE TITLE
React Native version is not working in latest XCode or Android?

### ISSUE THREAD

**Issue by dsteinman** [alibaba/GCanvas#166]
Hi, I'm trying out this project and cannot get it to work.  Once I did an npm install it has broken both versions of the freshly create rnative app.  I didn't even add GCanvas to the react app JS code yet, I just did

```
npm install @gcanvas/core --save
npm install react-native-gcanvas --save
```

Then I run `npx react-native run-android` and receive this error:

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/dstein/MyGame/node_modules/react-native-gcanvas/android/build.gradle' line: 35

* What went wrong:
A problem occurred evaluating project ':react-native-gcanvas'.
> Extension with name 'sdks' does not exist. Currently registered extension names: [ext, _internalAndroidGradlePluginDependencyCheckerRegistered]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
```

IOS also fails:

```
/Users/dstein/MyGame/node_modules/react-native-gcanvas/ios/RCTGCanvasView.h:22:9: fatal error: 'React/RCTView.h' file not found
#import <React/RCTView.h>
        ^~~~~~~~~~~~~~~~~
1 error generated.
```

I would suggest making an example project that people can refer to.

**Comment by flyskywhy** [comment]
Since Alibaba [feat: delete weex bridge & reactive bridge](https://github.com/alibaba/GCanvas/commit/1bbee40a16c0c5da58698e2892ba33f836eedb70), here comes the [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) npm package.

After months work, [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) runs well on Android and iOS, fix several bugs and add `feat: support drawImage() from require('some.png') on Android, iOS and Web` described in [Changelog.md](https://github.com/flyskywhy/react-native-gcanvas/blob/master/docs/Changelog.md), refactor with the detailed [Example As Usage](https://github.com/flyskywhy/react-native-gcanvas#example-as-usage) in README.md.

With [Performance Test Result](https://github.com/flyskywhy/react-native-gcanvas#performance-test-result), and [Convenient With Browser-like canvas APIs](https://github.com/flyskywhy/react-native-gcanvas#convenient-with-browser-like-canvas-apis) with the easily `<canvas/>` ported example [react-native-particles-bg](https://github.com/flyskywhy/react-native-particles-bg) runs on Android, iOS and Web, `@flyskywhy/react-native-gcanvas` is the best choice for now :yum:
