### ISSUE TITLE
Issues using with ReactNative

### ISSUE THREAD

**Issue by runrevben** [alibaba/GCanvas#183]
I've followed the guidelines to integrate with ReactNative (https://alibaba.github.io/GCanvas/docs/Integrate%20GCanvas%20on%20ReactNative.html) but I'm just running into build errors.

`RCTGCanvasView.h:22:9: 'React/RCTView.h' file not found`

I've tried both the semi automatic and the manual install methods a number of times but ultimately hit the same build issues. 

I'm using RN 0.63.2.

Here is my link binaries:
<img width="571" alt="Screenshot 2020-11-23 at 17 31 53" src="https://user-images.githubusercontent.com/3985826/99995216-f783bf80-2db1-11eb-9780-64aa3e047759.png">

And here is my search path:
<img width="532" alt="Screenshot 2020-11-23 at 17 33 38" src="https://user-images.githubusercontent.com/3985826/99995275-0c605300-2db2-11eb-926f-fcbe25785af2.png">

The above was set running 

`
yarn add @gcanvas/core --save
yarn react-native-gcanvas --save
react-native link react-native-gcanvas
`

Thanks,

Ben

**Comment by flyskywhy** [comment]
@runrevben 

Since Alibaba [feat: delete weex bridge & reactive bridge](https://github.com/alibaba/GCanvas/commit/1bbee40a16c0c5da58698e2892ba33f836eedb70), here comes the [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) npm package.

After months work, [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) runs well on Android and iOS, fix several bugs and add `feat: support drawImage() from require('some.png') on Android, iOS and Web` described in [Changelog.md](https://github.com/flyskywhy/react-native-gcanvas/blob/master/docs/Changelog.md), refactor with the detailed [Example As Usage](https://github.com/flyskywhy/react-native-gcanvas#example-as-usage) in README.md.

With [Performance Test Result](https://github.com/flyskywhy/react-native-gcanvas#performance-test-result), and [Convenient With Browser-like canvas APIs](https://github.com/flyskywhy/react-native-gcanvas#convenient-with-browser-like-canvas-apis) with the easily `<canvas/>` ported example [react-native-particles-bg](https://github.com/flyskywhy/react-native-particles-bg) runs on Android, iOS and Web, `@flyskywhy/react-native-gcanvas` is the best choice for now :yum:
