### ISSUE TITLE
Cant find RCTGCanvasView on android for react native bridge

### ISSUE THREAD

**Issue by DavidGOrtega** [alibaba/GCanvas#26]
Hi, 

according to 

```
import React, { Component, PropTypes } from 'react';
import { requireNativeComponent, View } from 'react-native';

var RCTGCanvasView = requireNativeComponent('RCTGCanvasView', GCanvasView);

export default class GCanvasView extends Component {
	static propTypes = {
		// isOffscreen: PropTypes.bool,
		...View.propTypes
	};

	render() {
		return ( <RCTGCanvasView {...this.props} /> );
	};
}
```

GCanvasView is the native component RCTGCanvasView however I cant find the android implementation, nor using REACT_CLASS either.

**Comment by hejian1639** [comment]
hi DavidGOrtega,

do you mean can't find out RCTGCanvasView?
actually there is a name issue, please try to use 'GCanvasView' instead.

**Comment by DavidGOrtega** [comment]
Hi @hejian1639 

actually I mean that I can't find the android native component RCTGCanvasView. The code that I pasted before is the js code of GCanvasView and it's a wrapper over the native component. Where I can find the RCTGCanvasView on android? I do a search in the project but I just only find it for iOS.

**Comment by fREEDtICE** [comment]
Hi,@DavidGOrtega,https://alibaba.github.io/GCanvas/docs/Integrate%20GCanvas%20on%20ReactNative.html

**Comment by pongponglau** [comment]
I cannot find RCTGCanvasView on android too. Where can i find it?

Thanks a lot

**Comment by flyskywhy** [comment]
@DavidGOrtega @pongponglau 

Since Alibaba [feat: delete weex bridge & reactive bridge](https://github.com/alibaba/GCanvas/commit/1bbee40a16c0c5da58698e2892ba33f836eedb70), here comes the [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) npm package.

After months work, [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) runs well on Android and iOS, fix several bugs and add `feat: support drawImage() from require('some.png') on Android, iOS and Web` described in [Changelog.md](https://github.com/flyskywhy/react-native-gcanvas/blob/master/docs/Changelog.md), refactor with the detailed [Example As Usage](https://github.com/flyskywhy/react-native-gcanvas#example-as-usage) in README.md.

With [Performance Test Result](https://github.com/flyskywhy/react-native-gcanvas#performance-test-result), and [Convenient With Browser-like canvas APIs](https://github.com/flyskywhy/react-native-gcanvas#convenient-with-browser-like-canvas-apis) with the easily `<canvas/>` ported example [react-native-particles-bg](https://github.com/flyskywhy/react-native-particles-bg) runs on Android, iOS and Web, `@flyskywhy/react-native-gcanvas` is the best choice for now :yum:
