### ISSUE TITLE
React Native: Android Sample don't work

### ISSUE THREAD

**Issue by diov** [alibaba/GCanvas#42]
node: v10.1.0
react-native-cli: 2.0.1
react-native: 0.55.4

按照文档接入的 Android Sample，运行之后显示

```
Error while updating property 'backgroundColor' of a view managed by: GCanvasView

null

TextureView doesn't support displaying a background drawable
```

**Comment by flyskywhy** [comment]
@diov [fix: `TextureView doesn't support displaying a background drawable` since Android API 24](https://github.com/flyskywhy/react-native-gcanvas/commit/31933be)

Since Alibaba [feat: delete weex bridge & reactive bridge](https://github.com/alibaba/GCanvas/commit/1bbee40a16c0c5da58698e2892ba33f836eedb70), here comes the [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) npm package.

After months work, [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) runs well on Android and iOS, fix several bugs and add `feat: support drawImage() from require('some.png') on Android, iOS and Web` described in [Changelog.md](https://github.com/flyskywhy/react-native-gcanvas/blob/master/docs/Changelog.md), refactor with the detailed [Example As Usage](https://github.com/flyskywhy/react-native-gcanvas#example-as-usage) in README.md.

With [Performance Test Result](https://github.com/flyskywhy/react-native-gcanvas#performance-test-result), and [Convenient With Browser-like canvas APIs](https://github.com/flyskywhy/react-native-gcanvas#convenient-with-browser-like-canvas-apis) with the easily `<canvas/>` ported example [react-native-particles-bg](https://github.com/flyskywhy/react-native-particles-bg) runs on Android, iOS and Web, `@flyskywhy/react-native-gcanvas` is the best choice for now :yum:
