### ISSUE TITLE
Integration document and exercises for react-native

### ISSUE THREAD

**Issue by natarajanandh** [alibaba/GCanvas#57]
Documentation and exercises is big time missing for react-native integration. I have tried both ways but it's not working like expected.

Kindly create advanced document for the android and IOS integration along with exercise. Since GCanvas looking promising for react-native but lack of documentations and exercises.

Please improve it, which will help for many developers especially those want to use canvas.

**Comment by flyskywhy** [comment]
@natarajanandh 

Since Alibaba [feat: delete weex bridge & reactive bridge](https://github.com/alibaba/GCanvas/commit/1bbee40a16c0c5da58698e2892ba33f836eedb70), here comes the [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) npm package.

After months work, [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) runs well on Android and iOS, fix several bugs and add `feat: support drawImage() from require('some.png') on Android, iOS and Web` described in [Changelog.md](https://github.com/flyskywhy/react-native-gcanvas/blob/master/docs/Changelog.md), refactor with the detailed [Example As Usage](https://github.com/flyskywhy/react-native-gcanvas#example-as-usage) in README.md.

With [Performance Test Result](https://github.com/flyskywhy/react-native-gcanvas#performance-test-result), and [Convenient With Browser-like canvas APIs](https://github.com/flyskywhy/react-native-gcanvas#convenient-with-browser-like-canvas-apis) with the easily `<canvas/>` ported example [react-native-particles-bg](https://github.com/flyskywhy/react-native-particles-bg) runs on Android, iOS and Web, `@flyskywhy/react-native-gcanvas` is the best choice for now :yum:
