### ISSUE TITLE
Weak support for react native

### ISSUE THREAD

**Issue by Kielan** [alibaba/GCanvas#69]
I have been using react native with this module for a while now, I have to leave a note to anyone trying to use this module with react native, it does not work following the readme instructions. I may leave a pull request at some point.

**Comment by Kielan** [comment]
please update these docs. I had this working with the search paths custom configured. I am trying to adapt this to latest react native to improve performance, but the last docs are from april 9, and they were incorrect when written.

https://github.com/alibaba/GCanvas/blob/dev/GCanvas/docs/Guide_Setup_ReactNative.md

**Comment by pengcheng** [comment]
+1, especially for Android.
There are several problems I found:
1, If use automatic installation with the following commands:
npm install gcanvas.js --save
npm install react-native-gcanvas --save
react-native link react-native-gcanvas

It can not build, there are 2 compile problems in bridge java code and incorrect package name of com.taobao.gcanvas.bridges.rn.GReactPackage

2, If use manual installation, it can build, but the sample App.js code can not word because backgroundColor is not an valid style name of GCanvasView.

Seems the latest version of gcanvas.js/react-native-gcanvas are not the one in manual installation section and the latest version contains compile errors but he versions in manual installation are not compatible with the example.

And the biggest problem is that target APK of both 2 methods (after fixing the bugs) does not contains the native .so file,  eventually the app crashes...

**Comment by drewandre** [comment]
@jwxbond asking the same question here as I did on #153 - there doesn't seem to be support for react-native 0.6x (mainly auto linking). Does your team plan on continuing support for react-native?

**Comment by flyskywhy** [comment]
@Kielan @pengcheng @drewandre 

Since Alibaba [feat: delete weex bridge & reactive bridge](https://github.com/alibaba/GCanvas/commit/1bbee40a16c0c5da58698e2892ba33f836eedb70), here comes the [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) npm package.

After months work, [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) runs well on Android and iOS, fix several bugs and add `feat: support drawImage() from require('some.png') on Android, iOS and Web` described in [Changelog.md](https://github.com/flyskywhy/react-native-gcanvas/blob/master/docs/Changelog.md), refactor with the detailed [Example As Usage](https://github.com/flyskywhy/react-native-gcanvas#example-as-usage) in README.md.

With [Performance Test Result](https://github.com/flyskywhy/react-native-gcanvas#performance-test-result), and [Convenient With Browser-like canvas APIs](https://github.com/flyskywhy/react-native-gcanvas#convenient-with-browser-like-canvas-apis) with the easily `<canvas/>` ported example [react-native-particles-bg](https://github.com/flyskywhy/react-native-particles-bg) runs on Android, iOS and Web, `@flyskywhy/react-native-gcanvas` is the best choice for now :yum:
